version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    hostname: mongodb
    container_name: mongodb
    env_file:
      - ./docker/.env
    networks:
      - database
    volumes:
      - mongo_data:/data/db
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
  dnd_bot:
    image: ${CI_REGISTRY_IMAGE-local}/dndbot:${CI_COMMIT_SHORT_SHA-local}
    depends_on:
      - mongodb
    build:
      context: .
    env_file:
      - ./docker/.env
    networks:
      - database
networks:
  database:

volumes:
  mongo_data: